typedef struct point { int x, y; } point;

/* Global variables */

char   char_global;
int    int_global;
float  flt_global;

point  struct_global;
int    tab_global[10];

/* Procedures, functions, parameters...
 *
 * char_funct: 
 * - the char argument will be received as an int,
 *   so the frontend then converts it (in place) to a char.
 *   Then the addition converts the char to an int...
 *   The result of the addition is then converted to the function type,
 *   however it's char so it is then finally converted to int again!!!
 *   => better to never use char params, nor char return type.
 *
 * flt_funct:
 * - the frontend adds float values without converting them to double!
 *
 * struct_funct:
 * - a void return is generated by the frontend,
 *   and the structure for the result is given by the caller.
 *   Before the void return, the frontend gives an ASGNB node that
 *   aims to copy the structure given by the return instruction to the
 *   structure given by the caller.
 *
 * char_ptr_funct, int_ptr_funt and struct_ptr_funct:
 * - the frontend wants to convert the returned pointer to unsigned
 *
 */

void   proc(void) {}
int    int_funct(int param) { return param+3; }
char   char_funct(char param) { return 3+param; }
float  flt_funct(float param) { return param+3.0F; }
double dbl_funct(double param) { return param+3.0; }

point  struct_funct(point param) { point p2; p2.x = p2.y = param.y+3; return p2; }
char*  char_ptr_funct(char* param) { return param+3; }
int*   int_ptr_funct(int param[]) { return param+3; }
point* struct_ptr_funct(point *param) { param->y += 3; return param; }

/* Global pointer variables */

char*  char_ptr_global = &char_global;
int*   int_ptr_global  = &tab_global[2]+2;
float* flt_ptr_global = &flt_global;
point* struct_ptr_global = &struct_global;
int    (*fct_ptr_global)(int) = int_funct;

int main(void)
{

/* local variables...
 *
 * ASGNB is used to initialize tab_local from a global constant...
 *
 */

int    int_local;
char   char_local;
float  flt_local;

point  struct_local;
int    tab_local[] = { 1, 1, 2, 3, 5, 8 };

/* Local pointer variables */

char*  char_ptr_local = &char_local;
int*   int_ptr_local  = &tab_local[2]+2;
float* flt_ptr_local = &flt_local;
point* struct_ptr_local = &struct_local;
int    (*fct_ptr_local)(int) = int_funct;

/* function calls, arguments */

proc();

char_local  = char_funct(char_global);
int_global = int_funct(int_global);
flt_local   = flt_funct(flt_global);

struct_local = struct_funct(struct_global);
struct_global = struct_funct(struct_local);

char_ptr_global = char_ptr_funct(char_ptr_local+2);
char_ptr_local = char_ptr_funct("hello");
int_ptr_local = int_ptr_funct(tab_global);
int_ptr_global = int_ptr_funct(tab_local);
struct_ptr_local = struct_ptr_funct(struct_ptr_global);

int_global = (*fct_ptr_global)(int_global);
int_local  = (*fct_ptr_local)(int_local);
}
