typedef struct point { int x, y; } point;

/* Global variables */

char   char_global = 'A';
int    int_global  = 1;
float  flt_global  = 1.0F;
double dbl_global  = 1.0;

point  struct_global = { 1, 3 };
int    tab_global[10] = { 0, 1, 1, 2, 3, 5 };

int    int_funct(int param) { return param+3; }

/* char_funct: 
 * - the char argument will be received as an int,
 *   so the frontend then converts it (in place) to a char.
 *   Then the addition converts the char to an int...
 *   The result of the addition is then converted to the function type,
 *   however it's char so it is then finally converted to int again!!!
 *   => better to never use char params, nor char return type.
 */

char   char_funct(char param) { return 3+param; }

/*
 * flt_funct:
 * - the frontend adds float values without converting them to double!
 */
float  flt_funct(float param) { return param+3.0F; }

double dbl_funct(double param) { return param+3.0; }


/*
 * struct_funct:
 * - a void return is generated by the frontend,
 *   and the structure for the result is given by the caller.
 *   Before the void return, the frontend gives an ASGNB node that
 *   aims to copy the structure given by the return instruction to the
 *   structure given by the caller.
 */
point  struct_funct(point param) { point p2; p2.x = p2.y = param.y+3; return p2; }

/*
 * char_ptr_funct, int_ptr_funt and struct_ptr_funct:
 * - the frontend wants to convert the returned pointer to unsigned
 */
char*  char_ptr_funct(char* param) { return param+3; }

int*   int_ptr_funct(int param[]) { return param+3; }

point* struct_ptr_funct(point *param) { param->y += 3; return param; }

/* Global pointer variables */

char*  char_ptr_global = &char_global;
int*   int_ptr_global  = &tab_global[2]+2;
float* flt_ptr_global = &flt_global;
point* struct_ptr_global = &struct_global;
int    (*fct_ptr_global)(int) = int_funct;

void check(int result, int expected, char *msg) {
    if (result == expected)  // putchar('.');
        printf("%s test ok\n", msg);
    else printf("%s test fails\n-> result is %d, expecting %d\n", msg, result, expected);
}

void simple_tests() {
    int    int_local;
    char   char_local;
    float  flt_local;
    double dbl_local=1.0;  

    check(int_global, 1, "int funct0");
    int_local = int_funct(int_global);
    check(int_local, 4, "int funct1");
    check(int_global, 1, "int funct1");

    int_global = int_funct(int_global);
    check(int_global, 4, "int funct2");

    char_local = char_funct(char_global);
    check(char_local, 'D' , "char funct");

    flt_local  = flt_funct(flt_global);
    check((int)flt_local, 4, "flt funct");

    dbl_global = dbl_funct(dbl_local); 
    check((int)int_global, 4, "dbl funct");
}

void simple_ptr_tests() {
/*
 * NB: ASGNB is used to initialize tab_local from a global constant...
 */
    int  tab_local[] = { 1, 1, 2, 3, 5, 8 };
    int  * int_ptr_local  = &tab_local[1]+1;
    char char_local[] = "hello";
    char * char_ptr_local = &char_local[2]+1;

    int_ptr_local   = int_ptr_funct(tab_global);
    check((int)int_ptr_local, (int)(tab_global+3), "int ptr funct1");

    int_ptr_global  = int_ptr_funct(tab_local);
    check((int)int_ptr_global, (int)(tab_local+3), "int ptr funct2");

    char_ptr_global = char_ptr_funct(char_ptr_local+2);
    check((int)char_ptr_global, (int)(char_ptr_local+5), "char ptr funct1");

    char_ptr_local  = char_ptr_funct("world");
    check(char_ptr_local[0], 'l', "char ptr funct2");

}

void fct_ptr_tests() {
    int int_local;
    int (*fct_ptr_local)(int) = int_funct;

    int_local = (*fct_ptr_global)(int_global);
    check(int_local, int_global+3, "fct ptr1");

    int_global  = (*fct_ptr_local)(int_local);
    check(int_global, int_local+3, "fct ptr2");

}

void struct_tests() {
    point  struct_local;
    point* struct_ptr_local = &struct_local;
    struct_ptr_global->y = 1;

    check(struct_global.y, 1, "struct funct0");

    struct_local = struct_funct(struct_global);
    check(struct_local.y, 4, "struct funct1");

    struct_global = struct_funct(struct_local);
    check(struct_global.y, 7, "struct funct2");

    struct_ptr_local = struct_ptr_funct(struct_ptr_global);
    check((int)struct_ptr_local, (int)struct_ptr_global, "struct ptr funct");
    check(struct_ptr_local->y, 10, "struct ptr funct");

}

void addr_tests()
{
    int a = 1, b;
    b = a + (int)&a;
    b = (int)&a + a;
    b = a -  (int)&a;
    b = (int)&a - a;
    b = a * (int)&a;
    b = (int)&a * a;
    b = (int)&a / a;
    b = a / (int)&a;
    b = a & (int)&a;
    b = (int)&a & a;
}

int main(void)
{
    simple_tests();
    simple_ptr_tests();
    fct_ptr_tests();
    struct_tests();
    printf("\nAll tests done\n");
}
